AllCops:
  NewCops: enable
  SuggestExtensions: false
  TargetRubyVersion: 2.5.0

Gemspec/RequiredRubyVersion:
  Enabled: False

Layout/LineLength:
  Max: 80

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Metrics/AbcSize:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Style/ExplicitBlockArgument:
  Enabled: false

# Disabling for now to support Ruby 2.3.
Style/HashTransformValues:
  Enabled: false
